# Generated by Django 4.2.3 on 2024-04-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_data_de_entrega_entrega_data_de_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='data_de_entrega',
            new_name='dataEntrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='endereco_de_entrega',
            new_name='enderecoEntrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='nome_do_cliente',
            new_name='nomeDoCliente',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='quantidade_disponivel',
            new_name='disponibilidadeDoProduto',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='nome_do_produto',
            new_name='nomeDoProduto',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='preco_unitario',
            new_name='valorUnidade',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='entrega',
            new_name='entregaDoItem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nome_do_produto',
            new_name='nomeDoItem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='preco_unitario',
            new_name='valorUnidadeItem',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='metodo_de_pagamento',
            new_name='metodoPagamento',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='valor_total',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='quantidade_disponivel',
            new_name='disponibilidadeDoProduto',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='nome_do_produto',
            new_name='nomeDoProduto',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='preco_unitario',
            new_name='valorUnidade',
        ),
    ]
